### ISSUE TITLE
Enable students to see grades

### ISSUE THREAD

**Issue by MadSmith17** [MadSmith17/Scrum_GitHubFlow#1]
Persona: Student
Feature: View Grades
Business Value: Improve student experience

**Comment by MadSmith17** [comment]
- **User Story:**
      - For students in school.
      - For students to be able to see their grades that their teachers have given them.
      - Students can easily see their grades from anywhere.

   - **Detailed Description:**
      - Create a program that allows students to access their grades from anywhere once the teacher publishes them.

   - **Task List:**
      - Create assignments
      - Allow teachers to input grades for the assignments
      - Students can see the grades the teachers published for the assignments

   - **Acceptance Criteria:**
     - Students must be able to view their grades.

   - **Acceptance Tests:**
      - Create multiple assignments and input grades for each and see if the student/user can see the grades from their side.

   - **Proper Labels:**
      - Feature

**Comment by eyu776** [comment]
You can edit the content of your issue. 

In the future, you should edit the issue to include all of the contents (user story, task list, acceptance tests/criteria, etc.) instead of leaving it blank and writing it into a new comment within the issue.

**Comment by eyu776** [comment]
In the future you should format commits like (using [your commit](https://github.com/MadSmith17/Scrum_GitHubFlow/commit/b7908ec472168e6ba52b80961e13b2c95e2043bf) as an example):

Add: view grades
```{must have BLANK new line here}```
Initial implementation of view grades feature.

```
{you can potentially add steps/changes made in the commit}
* change 1
* change 2
* change 3
```

Issue #1
